// Nifty 500 + Top Indian & US stocks with sector mapping
export const STOCK_UNIVERSE: { symbol: string; name: string; sector: string }[] = [
  // ─── BANKING & FINANCE ──────────────────────────────────────────
  { symbol: "HDFCBANK:NSE", name: "HDFC Bank", sector: "Banking" },
  { symbol: "ICICIBANK:NSE", name: "ICICI Bank", sector: "Banking" },
  { symbol: "SBIN:NSE", name: "State Bank of India", sector: "Banking" },
  { symbol: "KOTAKBANK:NSE", name: "Kotak Mahindra Bank", sector: "Banking" },
  { symbol: "AXISBANK:NSE", name: "Axis Bank", sector: "Banking" },
  { symbol: "INDUSINDBK:NSE", name: "IndusInd Bank", sector: "Banking" },
  { symbol: "BANDHANBNK:NSE", name: "Bandhan Bank", sector: "Banking" },
  { symbol: "FEDERALBNK:NSE", name: "Federal Bank", sector: "Banking" },
  { symbol: "IDFCFIRSTB:NSE", name: "IDFC First Bank", sector: "Banking" },
  { symbol: "PNB:NSE", name: "Punjab National Bank", sector: "Banking" },
  { symbol: "BANKBARODA:NSE", name: "Bank of Baroda", sector: "Banking" },
  { symbol: "CANBK:NSE", name: "Canara Bank", sector: "Banking" },
  { symbol: "UNIONBANK:NSE", name: "Union Bank", sector: "Banking" },
  { symbol: "BAJFINANCE:NSE", name: "Bajaj Finance", sector: "Finance" },
  { symbol: "BAJAJFINSV:NSE", name: "Bajaj Finserv", sector: "Finance" },
  { symbol: "HDFCLIFE:NSE", name: "HDFC Life", sector: "Finance" },
  { symbol: "SBILIFE:NSE", name: "SBI Life Insurance", sector: "Finance" },
  { symbol: "ICICIGI:NSE", name: "ICICI Lombard", sector: "Finance" },
  { symbol: "MUTHOOTFIN:NSE", name: "Muthoot Finance", sector: "Finance" },
  { symbol: "CHOLAFIN:NSE", name: "Cholamandalam Finance", sector: "Finance" },
  { symbol: "M&MFIN:NSE", name: "M&M Financial", sector: "Finance" },
  { symbol: "LICHSGFIN:NSE", name: "LIC Housing Finance", sector: "Finance" },
  { symbol: "RECLTD:NSE", name: "REC Ltd", sector: "Finance" },
  { symbol: "PFC:NSE", name: "Power Finance Corp", sector: "Finance" },

  // ─── IT & TECHNOLOGY ────────────────────────────────────────────
  { symbol: "TCS:NSE", name: "Tata Consultancy Services", sector: "IT" },
  { symbol: "INFY:NSE", name: "Infosys", sector: "IT" },
  { symbol: "WIPRO:NSE", name: "Wipro", sector: "IT" },
  { symbol: "HCLTECH:NSE", name: "HCL Technologies", sector: "IT" },
  { symbol: "TECHM:NSE", name: "Tech Mahindra", sector: "IT" },
  { symbol: "LTIM:NSE", name: "LTIMindtree", sector: "IT" },
  { symbol: "MPHASIS:NSE", name: "Mphasis", sector: "IT" },
  { symbol: "PERSISTENT:NSE", name: "Persistent Systems", sector: "IT" },
  { symbol: "COFORGE:NSE", name: "Coforge", sector: "IT" },
  { symbol: "OFSS:NSE", name: "Oracle Fin Services", sector: "IT" },
  { symbol: "KPITTECH:NSE", name: "KPIT Technologies", sector: "IT" },
  { symbol: "TATAELXSI:NSE", name: "Tata Elxsi", sector: "IT" },
  { symbol: "RATEGAIN:NSE", name: "RateGain Travel", sector: "IT" },
  { symbol: "ZENSARTECH:NSE", name: "Zensar Technologies", sector: "IT" },

  // ─── ENERGY & OIL ───────────────────────────────────────────────
  { symbol: "RELIANCE:NSE", name: "Reliance Industries", sector: "Energy" },
  { symbol: "ONGC:NSE", name: "ONGC", sector: "Energy" },
  { symbol: "BPCL:NSE", name: "BPCL", sector: "Energy" },
  { symbol: "IOC:NSE", name: "Indian Oil Corp", sector: "Energy" },
  { symbol: "HINDPETRO:NSE", name: "HPCL", sector: "Energy" },
  { symbol: "GAIL:NSE", name: "GAIL India", sector: "Energy" },
  { symbol: "PETRONET:NSE", name: "Petronet LNG", sector: "Energy" },
  { symbol: "CASTROLIND:NSE", name: "Castrol India", sector: "Energy" },

  // ─── POWER & UTILITIES ──────────────────────────────────────────
  { symbol: "NTPC:NSE", name: "NTPC", sector: "Power" },
  { symbol: "POWERGRID:NSE", name: "Power Grid Corp", sector: "Power" },
  { symbol: "ADANIPOWER:NSE", name: "Adani Power", sector: "Power" },
  { symbol: "TATAPOWER:NSE", name: "Tata Power", sector: "Power" },
  { symbol: "CESC:NSE", name: "CESC", sector: "Power" },
  { symbol: "TORNTPOWER:NSE", name: "Torrent Power", sector: "Power" },
  { symbol: "SJVN:NSE", name: "SJVN", sector: "Power" },
  { symbol: "NHPC:NSE", name: "NHPC", sector: "Power" },
  { symbol: "IRCON:NSE", name: "IRCON International", sector: "Power" },

  // ─── PHARMA & HEALTHCARE ────────────────────────────────────────
  { symbol: "SUNPHARMA:NSE", name: "Sun Pharma", sector: "Pharma" },
  { symbol: "DRREDDY:NSE", name: "Dr Reddy's Labs", sector: "Pharma" },
  { symbol: "CIPLA:NSE", name: "Cipla", sector: "Pharma" },
  { symbol: "DIVISLAB:NSE", name: "Divi's Laboratories", sector: "Pharma" },
  { symbol: "APOLLOHOSP:NSE", name: "Apollo Hospitals", sector: "Pharma" },
  { symbol: "LUPIN:NSE", name: "Lupin", sector: "Pharma" },
  { symbol: "AUROPHARMA:NSE", name: "Aurobindo Pharma", sector: "Pharma" },
  { symbol: "BIOCON:NSE", name: "Biocon", sector: "Pharma" },
  { symbol: "TORNTPHARM:NSE", name: "Torrent Pharma", sector: "Pharma" },
  { symbol: "GLENMARK:NSE", name: "Glenmark Pharma", sector: "Pharma" },
  { symbol: "IPCA:NSE", name: "IPCA Laboratories", sector: "Pharma" },
  { symbol: "ABBOTINDIA:NSE", name: "Abbott India", sector: "Pharma" },
  { symbol: "ALKEM:NSE", name: "Alkem Laboratories", sector: "Pharma" },
  { symbol: "MANKIND:NSE", name: "Mankind Pharma", sector: "Pharma" },
  { symbol: "MAXHEALTH:NSE", name: "Max Healthcare", sector: "Pharma" },

  // ─── CONSUMER GOODS / FMCG ──────────────────────────────────────
  { symbol: "HINDUNILVR:NSE", name: "Hindustan Unilever", sector: "FMCG" },
  { symbol: "ITC:NSE", name: "ITC Ltd", sector: "FMCG" },
  { symbol: "NESTLEIND:NSE", name: "Nestle India", sector: "FMCG" },
  { symbol: "BRITANNIA:NSE", name: "Britannia Industries", sector: "FMCG" },
  { symbol: "TATACONSUM:NSE", name: "Tata Consumer", sector: "FMCG" },
  { symbol: "DABUR:NSE", name: "Dabur India", sector: "FMCG" },
  { symbol: "GODREJCP:NSE", name: "Godrej Consumer", sector: "FMCG" },
  { symbol: "MARICO:NSE", name: "Marico", sector: "FMCG" },
  { symbol: "COLPAL:NSE", name: "Colgate-Palmolive", sector: "FMCG" },
  { symbol: "EMAMILTD:NSE", name: "Emami", sector: "FMCG" },
  { symbol: "VBL:NSE", name: "Varun Beverages", sector: "FMCG" },
  { symbol: "RADICO:NSE", name: "Radico Khaitan", sector: "FMCG" },
  { symbol: "UBL:NSE", name: "United Breweries", sector: "FMCG" },

  // ─── AUTOMOBILE ─────────────────────────────────────────────────
  { symbol: "MARUTI:NSE", name: "Maruti Suzuki", sector: "Auto" },
  { symbol: "TATAMOTORS:NSE", name: "Tata Motors", sector: "Auto" },
  { symbol: "M&M:NSE", name: "Mahindra & Mahindra", sector: "Auto" },
  { symbol: "BAJAJ-AUTO:NSE", name: "Bajaj Auto", sector: "Auto" },
  { symbol: "HEROMOTOCO:NSE", name: "Hero MotoCorp", sector: "Auto" },
  { symbol: "EICHERMOT:NSE", name: "Eicher Motors", sector: "Auto" },
  { symbol: "TVSMOTOR:NSE", name: "TVS Motor", sector: "Auto" },
  { symbol: "ASHOKLEY:NSE", name: "Ashok Leyland", sector: "Auto" },
  { symbol: "BOSCHLTD:NSE", name: "Bosch", sector: "Auto" },
  { symbol: "MRF:NSE", name: "MRF", sector: "Auto" },
  { symbol: "BALKRISIND:NSE", name: "Balkrishna Industries", sector: "Auto" },
  { symbol: "APOLLOTYRE:NSE", name: "Apollo Tyres", sector: "Auto" },
  { symbol: "MOTHERSON:NSE", name: "Motherson Sumi", sector: "Auto" },
  { symbol: "EXIDEIND:NSE", name: "Exide Industries", sector: "Auto" },

  // ─── INFRASTRUCTURE & CONSTRUCTION ──────────────────────────────
  { symbol: "LT:NSE", name: "Larsen & Toubro", sector: "Infrastructure" },
  { symbol: "ADANIENT:NSE", name: "Adani Enterprises", sector: "Infrastructure" },
  { symbol: "ADANIPORTS:NSE", name: "Adani Ports", sector: "Infrastructure" },
  { symbol: "ADANIGREEN:NSE", name: "Adani Green Energy", sector: "Infrastructure" },
  { symbol: "LTTS:NSE", name: "L&T Technology Services", sector: "Infrastructure" },
  { symbol: "HAL:NSE", name: "Hindustan Aeronautics", sector: "Infrastructure" },
  { symbol: "BEL:NSE", name: "Bharat Electronics", sector: "Infrastructure" },
  { symbol: "BHEL:NSE", name: "BHEL", sector: "Infrastructure" },
  { symbol: "NCC:NSE", name: "NCC Ltd", sector: "Infrastructure" },
  { symbol: "NBCC:NSE", name: "NBCC India", sector: "Infrastructure" },
  { symbol: "IRB:NSE", name: "IRB Infrastructure", sector: "Infrastructure" },
  { symbol: "GMRINFRA:NSE", name: "GMR Airports", sector: "Infrastructure" },

  // ─── METALS & MINING ────────────────────────────────────────────
  { symbol: "TATASTEEL:NSE", name: "Tata Steel", sector: "Metals" },
  { symbol: "JSWSTEEL:NSE", name: "JSW Steel", sector: "Metals" },
  { symbol: "HINDALCO:NSE", name: "Hindalco Industries", sector: "Metals" },
  { symbol: "COALINDIA:NSE", name: "Coal India", sector: "Metals" },
  { symbol: "VEDL:NSE", name: "Vedanta", sector: "Metals" },
  { symbol: "NATIONALUM:NSE", name: "NALCO", sector: "Metals" },
  { symbol: "SAIL:NSE", name: "SAIL", sector: "Metals" },
  { symbol: "NMDC:NSE", name: "NMDC", sector: "Metals" },
  { symbol: "HINDCOPPER:NSE", name: "Hindustan Copper", sector: "Metals" },
  { symbol: "WELSPUNLIV:NSE", name: "Welspun Living", sector: "Metals" },

  // ─── CEMENT ─────────────────────────────────────────────────────
  { symbol: "ULTRACEMCO:NSE", name: "UltraTech Cement", sector: "Cement" },
  { symbol: "GRASIM:NSE", name: "Grasim Industries", sector: "Cement" },
  { symbol: "SHREECEM:NSE", name: "Shree Cement", sector: "Cement" },
  { symbol: "AMBUJACEM:NSE", name: "Ambuja Cements", sector: "Cement" },
  { symbol: "ACC:NSE", name: "ACC Ltd", sector: "Cement" },
  { symbol: "DALMIACHIN:NSE", name: "Dalmia Bharat", sector: "Cement" },
  { symbol: "RAMCOCEM:NSE", name: "Ramco Cements", sector: "Cement" },
  { symbol: "JKLAKSHMI:NSE", name: "JK Lakshmi Cement", sector: "Cement" },

  // ─── TELECOM ────────────────────────────────────────────────────
  { symbol: "BHARTIARTL:NSE", name: "Bharti Airtel", sector: "Telecom" },
  { symbol: "IDEA:NSE", name: "Vodafone Idea", sector: "Telecom" },
  { symbol: "INDUSTOWER:NSE", name: "Indus Towers", sector: "Telecom" },
  { symbol: "TATACOMM:NSE", name: "Tata Communications", sector: "Telecom" },

  // ─── CHEMICALS ──────────────────────────────────────────────────
  { symbol: "UPL:NSE", name: "UPL Ltd", sector: "Chemicals" },
  { symbol: "PIDILITIND:NSE", name: "Pidilite Industries", sector: "Chemicals" },
  { symbol: "SRF:NSE", name: "SRF Ltd", sector: "Chemicals" },
  { symbol: "AARTI:NSE", name: "Aarti Industries", sector: "Chemicals" },
  { symbol: "DEEPAKNTR:NSE", name: "Deepak Nitrite", sector: "Chemicals" },
  { symbol: "FINEORG:NSE", name: "Fine Organics", sector: "Chemicals" },
  { symbol: "NAVINFLUOR:NSE", name: "Navin Fluorine", sector: "Chemicals" },
  { symbol: "GNFC:NSE", name: "GNFC", sector: "Chemicals" },
  { symbol: "TATACHEM:NSE", name: "Tata Chemicals", sector: "Chemicals" },
  { symbol: "GSFC:NSE", name: "GSFC", sector: "Chemicals" },

  // ─── CONSUMER DURABLES & ELECTRONICS ────────────────────────────
  { symbol: "TITAN:NSE", name: "Titan Company", sector: "Consumer" },
  { symbol: "ASIANPAINT:NSE", name: "Asian Paints", sector: "Consumer" },
  { symbol: "HAVELLS:NSE", name: "Havells India", sector: "Consumer" },
  { symbol: "VOLTAS:NSE", name: "Voltas", sector: "Consumer" },
  { symbol: "BLUESTARCO:NSE", name: "Blue Star", sector: "Consumer" },
  { symbol: "WHIRLPOOL:NSE", name: "Whirlpool of India", sector: "Consumer" },
  { symbol: "VGUARD:NSE", name: "V-Guard Industries", sector: "Consumer" },
  { symbol: "CROMPTON:NSE", name: "Crompton Greaves", sector: "Consumer" },
  { symbol: "AMBER:NSE", name: "Amber Enterprises", sector: "Consumer" },
  { symbol: "DIXON:NSE", name: "Dixon Technologies", sector: "Consumer" },
  { symbol: "KAJARIACER:NSE", name: "Kajaria Ceramics", sector: "Consumer" },

  // ─── RETAIL & E-COMMERCE ────────────────────────────────────────
  { symbol: "TRENT:NSE", name: "Trent Ltd", sector: "Retail" },
  { symbol: "DMART:NSE", name: "Avenue Supermarts", sector: "Retail" },
  { symbol: "SHOPERSTOP:NSE", name: "Shoppers Stop", sector: "Retail" },
  { symbol: "ZOMATO:NSE", name: "Zomato", sector: "Retail" },
  { symbol: "NYKAA:NSE", name: "Nykaa (FSN E-Commerce)", sector: "Retail" },
  { symbol: "PAYTM:NSE", name: "Paytm", sector: "Retail" },
  { symbol: "DELHIVERY:NSE", name: "Delhivery", sector: "Retail" },

  // ─── RAILWAYS & DEFENCE ─────────────────────────────────────────
  { symbol: "IRCTC:NSE", name: "IRCTC", sector: "Railway" },
  { symbol: "RVNL:NSE", name: "Rail Vikas Nigam", sector: "Railway" },
  { symbol: "IRFC:NSE", name: "Indian Railway Finance", sector: "Railway" },
  { symbol: "IRCON:NSE", name: "IRCON International", sector: "Railway" },
  { symbol: "TITAGARH:NSE", name: "Titagarh Wagons", sector: "Railway" },
  { symbol: "COCHINSHIP:NSE", name: "Cochin Shipyard", sector: "Railway" },
  { symbol: "GRSE:NSE", name: "Garden Reach Shipbuilders", sector: "Railway" },
  { symbol: "MAZDOCK:NSE", name: "Mazagon Dock", sector: "Railway" },
  { symbol: "BEML:NSE", name: "BEML Ltd", sector: "Railway" },

  // ─── REAL ESTATE ────────────────────────────────────────────────
  { symbol: "DLF:NSE", name: "DLF Ltd", sector: "Real Estate" },
  { symbol: "GODREJPROP:NSE", name: "Godrej Properties", sector: "Real Estate" },
  { symbol: "PRESTIGE:NSE", name: "Prestige Estates", sector: "Real Estate" },
  { symbol: "OBEROIRLTY:NSE", name: "Oberoi Realty", sector: "Real Estate" },
  { symbol: "PHOENIXLTD:NSE", name: "Phoenix Mills", sector: "Real Estate" },
  { symbol: "BRIGADE:NSE", name: "Brigade Enterprises", sector: "Real Estate" },
  { symbol: "SOBHA:NSE", name: "Sobha Ltd", sector: "Real Estate" },
  { symbol: "MAHLIFE:NSE", name: "Mahindra Lifespace", sector: "Real Estate" },

  // ─── AGRICULTURE & FERTILISERS ──────────────────────────────────
  { symbol: "PIIND:NSE", name: "PI Industries", sector: "Agri" },
  { symbol: "CHAMBLFERT:NSE", name: "Chambal Fertilisers", sector: "Agri" },
  { symbol: "COROMANDEL:NSE", name: "Coromandel International", sector: "Agri" },
  { symbol: "RALLIS:NSE", name: "Rallis India", sector: "Agri" },
  { symbol: "KAVERI:NSE", name: "Kaveri Seed", sector: "Agri" },

  // ─── MEDIA & ENTERTAINMENT ──────────────────────────────────────
  { symbol: "ZEEL:NSE", name: "Zee Entertainment", sector: "Media" },
  { symbol: "SUNTV:NSE", name: "Sun TV Network", sector: "Media" },
  { symbol: "SAREGAMA:NSE", name: "Saregama India", sector: "Media" },
  { symbol: "NAZARA:NSE", name: "Nazara Technologies", sector: "Media" },
  { symbol: "PVR:NSE", name: "PVR Inox", sector: "Media" },

  // ─── AVIATION & LOGISTICS ───────────────────────────────────────
  { symbol: "INDIGO:NSE", name: "IndiGo (InterGlobe)", sector: "Aviation" },
  { symbol: "BLUEDART:NSE", name: "Blue Dart Express", sector: "Aviation" },
  { symbol: "GESHIP:NSE", name: "Great Eastern Shipping", sector: "Aviation" },
  { symbol: "CONCOR:NSE", name: "Container Corp of India", sector: "Aviation" },
  { symbol: "MAHLOG:NSE", name: "Mahindra Logistics", sector: "Aviation" },

  // ─── ADDITIONAL BANKING ─────────────────────────────────────────
  { symbol: "YESBANK:NSE", name: "Yes Bank", sector: "Banking" },
  { symbol: "RBLBANK:NSE", name: "RBL Bank", sector: "Banking" },
  { symbol: "DCBBANK:NSE", name: "DCB Bank", sector: "Banking" },
  { symbol: "KTKBANK:NSE", name: "Karnataka Bank", sector: "Banking" },
  { symbol: "SOUTHBANK:NSE", name: "South Indian Bank", sector: "Banking" },
  { symbol: "KARURVYSYA:NSE", name: "Karur Vysya Bank", sector: "Banking" },
  { symbol: "CUB:NSE", name: "City Union Bank", sector: "Banking" },
  { symbol: "J&KBANK:NSE", name: "J&K Bank", sector: "Banking" },

  // ─── CAPITAL MARKETS ────────────────────────────────────────────
  { symbol: "BSE:NSE", name: "BSE Ltd", sector: "Capital Markets" },
  { symbol: "CDSL:NSE", name: "CDSL", sector: "Capital Markets" },
  { symbol: "MCX:NSE", name: "MCX India", sector: "Capital Markets" },
  { symbol: "CAMS:NSE", name: "CAMS", sector: "Capital Markets" },
  { symbol: "KFINTECH:NSE", name: "KFin Technologies", sector: "Capital Markets" },
  { symbol: "ANGELONE:NSE", name: "Angel One", sector: "Capital Markets" },
  { symbol: "MOTILALOFS:NSE", name: "Motilal Oswal Financial", sector: "Capital Markets" },
  { symbol: "HDFCAMC:NSE", name: "HDFC AMC", sector: "Capital Markets" },
  { symbol: "NIPPONLIFE:NSE", name: "Nippon India AMC", sector: "Capital Markets" },
  { symbol: "UTIAMC:NSE", name: "UTI AMC", sector: "Capital Markets" },
  { symbol: "ABCAPITAL:NSE", name: "Aditya Birla Capital", sector: "Capital Markets" },
  { symbol: "IIFLWAM:NSE", name: "IIFL Wealth Management", sector: "Capital Markets" },
  { symbol: "MANAPPURAM:NSE", name: "Manappuram Finance", sector: "Capital Markets" },

  // ─── ADDITIONAL FINANCE ─────────────────────────────────────────
  { symbol: "SUNDARMFIN:NSE", name: "Sundaram Finance", sector: "Finance" },
  { symbol: "MAHINDCIE:NSE", name: "Mahindra CIE Auto", sector: "Finance" },
  { symbol: "POONAWALLA:NSE", name: "Poonawalla Fincorp", sector: "Finance" },
  { symbol: "UGROCAP:NSE", name: "Ugro Capital", sector: "Finance" },
  { symbol: "CREDITACC:NSE", name: "CreditAccess Grameen", sector: "Finance" },

  // ─── ADDITIONAL IT ──────────────────────────────────────────────
  { symbol: "CYIENT:NSE", name: "Cyient", sector: "IT" },
  { symbol: "MASTEK:NSE", name: "Mastek", sector: "IT" },
  { symbol: "BIRLASOFT:NSE", name: "Birlasoft", sector: "IT" },
  { symbol: "TANLA:NSE", name: "Tanla Platforms", sector: "IT" },
  { symbol: "NAUKRI:NSE", name: "Info Edge (Naukri)", sector: "IT" },
  { symbol: "INDIAMART:NSE", name: "IndiaMart InterMESH", sector: "IT" },
  { symbol: "JUSTDIAL:NSE", name: "Just Dial", sector: "IT" },
  { symbol: "LATENTVIEW:NSE", name: "Latent View Analytics", sector: "IT" },
  { symbol: "HAPPSTMNDS:NSE", name: "Happiest Minds Tech", sector: "IT" },
  { symbol: "INTELLECT:NSE", name: "Intellect Design Arena", sector: "IT" },

  // ─── GAS DISTRIBUTION ───────────────────────────────────────────
  { symbol: "IGL:NSE", name: "Indraprastha Gas", sector: "Energy" },
  { symbol: "MGL:NSE", name: "Mahanagar Gas", sector: "Energy" },
  { symbol: "GUJGASLTD:NSE", name: "Gujarat Gas", sector: "Energy" },
  { symbol: "GSPL:NSE", name: "Gujarat State Petro", sector: "Energy" },
  { symbol: "MRPL:NSE", name: "MRPL", sector: "Energy" },

  // ─── ADDITIONAL PHARMA ──────────────────────────────────────────
  { symbol: "NATCO:NSE", name: "Natco Pharma", sector: "Pharma" },
  { symbol: "JBCHEPHARM:NSE", name: "JB Chemicals", sector: "Pharma" },
  { symbol: "GRANULES:NSE", name: "Granules India", sector: "Pharma" },
  { symbol: "PFIZER:NSE", name: "Pfizer India", sector: "Pharma" },
  { symbol: "GLAXO:NSE", name: "GSK Pharma India", sector: "Pharma" },
  { symbol: "SANOFI:NSE", name: "Sanofi India", sector: "Pharma" },
  { symbol: "ZYDUSLIFE:NSE", name: "Zydus Lifesciences", sector: "Pharma" },
  { symbol: "LAURUSLABS:NSE", name: "Laurus Labs", sector: "Pharma" },
  { symbol: "SUVEN:NSE", name: "Suven Pharmaceuticals", sector: "Pharma" },

  // ─── HEALTHCARE & DIAGNOSTICS ───────────────────────────────────
  { symbol: "FORTIS:NSE", name: "Fortis Healthcare", sector: "Healthcare" },
  { symbol: "ASTER:NSE", name: "Aster DM Healthcare", sector: "Healthcare" },
  { symbol: "NARAYANA:NSE", name: "Narayana Hrudayalaya", sector: "Healthcare" },
  { symbol: "KIMS:NSE", name: "Krishna Institute of Med Sciences", sector: "Healthcare" },
  { symbol: "RAINBOW:NSE", name: "Rainbow Children's Medicare", sector: "Healthcare" },
  { symbol: "METROPOLIS:NSE", name: "Metropolis Healthcare", sector: "Healthcare" },
  { symbol: "LALPATHLAB:NSE", name: "Dr Lal PathLabs", sector: "Healthcare" },
  { symbol: "THYROCARE:NSE", name: "Thyrocare Technologies", sector: "Healthcare" },
  { symbol: "VIJAYABANK:NSE", name: "Vijaya Diagnostics", sector: "Healthcare" },
  { symbol: "MEDANTA:NSE", name: "Global Health (Medanta)", sector: "Healthcare" },

  // ─── ADDITIONAL AUTO ────────────────────────────────────────────
  { symbol: "BHARATFORG:NSE", name: "Bharat Forge", sector: "Auto" },
  { symbol: "SUNDRMFAST:NSE", name: "Sundram Fasteners", sector: "Auto" },
  { symbol: "SCHAEFFLER:NSE", name: "Schaeffler India", sector: "Auto" },
  { symbol: "TIINDIA:NSE", name: "Tube Investments of India", sector: "Auto" },
  { symbol: "CEAT:NSE", name: "CEAT Ltd", sector: "Auto" },
  { symbol: "SUPRAJIT:NSE", name: "Suprajit Engineering", sector: "Auto" },
  { symbol: "ENDURANCE:NSE", name: "Endurance Technologies", sector: "Auto" },
  { symbol: "CRAFTSMAN:NSE", name: "Craftsman Automation", sector: "Auto" },
  { symbol: "SWARAJENG:NSE", name: "Swaraj Engines", sector: "Auto" },

  // ─── ADDITIONAL INFRASTRUCTURE / CAPITAL GOODS ──────────────────
  { symbol: "ABB:NSE", name: "ABB India", sector: "Infrastructure" },
  { symbol: "SIEMENS:NSE", name: "Siemens India", sector: "Infrastructure" },
  { symbol: "CUMMINSIND:NSE", name: "Cummins India", sector: "Infrastructure" },
  { symbol: "THERMAX:NSE", name: "Thermax Ltd", sector: "Infrastructure" },
  { symbol: "KECINFRA:NSE", name: "KEC International", sector: "Infrastructure" },
  { symbol: "AIAENG:NSE", name: "AIA Engineering", sector: "Infrastructure" },
  { symbol: "ELGIEQUIP:NSE", name: "Elgi Equipments", sector: "Infrastructure" },
  { symbol: "GRINDWELL:NSE", name: "Grindwell Norton", sector: "Infrastructure" },
  { symbol: "ESCORTS:NSE", name: "Escorts Kubota", sector: "Infrastructure" },
  { symbol: "CGPOWER:NSE", name: "CG Power & Industrial", sector: "Infrastructure" },
  { symbol: "TRITURBINE:NSE", name: "Triveni Turbine", sector: "Infrastructure" },
  { symbol: "ISGEC:NSE", name: "ISGEC Heavy Engineering", sector: "Infrastructure" },

  // ─── ADDITIONAL METALS ──────────────────────────────────────────
  { symbol: "APLAPOLLO:NSE", name: "APL Apollo Tubes", sector: "Metals" },
  { symbol: "RATNAMANI:NSE", name: "Ratnamani Metals", sector: "Metals" },
  { symbol: "JINDALSTEL:NSE", name: "Jindal Steel & Power", sector: "Metals" },
  { symbol: "MOIL:NSE", name: "MOIL", sector: "Metals" },
  { symbol: "STLTECH:NSE", name: "Sterlite Technologies", sector: "Metals" },
  { symbol: "TINPLATE:NSE", name: "Tinplate Company of India", sector: "Metals" },
  { symbol: "JSWENERGY:NSE", name: "JSW Energy", sector: "Power" },

  // ─── ADDITIONAL CHEMICALS ───────────────────────────────────────
  { symbol: "VINATIORG:NSE", name: "Vinati Organics", sector: "Chemicals" },
  { symbol: "ATUL:NSE", name: "Atul Ltd", sector: "Chemicals" },
  { symbol: "NOCIL:NSE", name: "NOCIL", sector: "Chemicals" },
  { symbol: "PCBL:NSE", name: "PCBL Ltd", sector: "Chemicals" },
  { symbol: "SUDARSCHEM:NSE", name: "Sudarshan Chemical", sector: "Chemicals" },
  { symbol: "GALAXYSURF:NSE", name: "Galaxy Surfactants", sector: "Chemicals" },
  { symbol: "BASF:NSE", name: "BASF India", sector: "Chemicals" },
  { symbol: "CLEAN:NSE", name: "Clean Science & Technology", sector: "Chemicals" },
  { symbol: "HFCL:NSE", name: "HFCL Ltd", sector: "Chemicals" },

  // ─── ADDITIONAL CONSUMER DURABLES ───────────────────────────────
  { symbol: "POLYCAB:NSE", name: "Polycab India", sector: "Consumer" },
  { symbol: "SUPREMEIND:NSE", name: "Supreme Industries", sector: "Consumer" },
  { symbol: "FINOLEXCAB:NSE", name: "Finolex Cables", sector: "Consumer" },
  { symbol: "SYMPHONY:NSE", name: "Symphony Ltd", sector: "Consumer" },
  { symbol: "ORIENTELEC:NSE", name: "Orient Electric", sector: "Consumer" },
  { symbol: "CERA:NSE", name: "Cera Sanitaryware", sector: "Consumer" },
  { symbol: "ASTRAL:NSE", name: "Astral Ltd", sector: "Consumer" },
  { symbol: "PRINCEPIPE:NSE", name: "Prince Pipes", sector: "Consumer" },

  // ─── ADDITIONAL RETAIL & E-COMMERCE ─────────────────────────────
  { symbol: "ABFRL:NSE", name: "Aditya Birla Fashion", sector: "Retail" },
  { symbol: "VEDANT:NSE", name: "Vedant Fashions (Manyavar)", sector: "Retail" },
  { symbol: "BATA:NSE", name: "Bata India", sector: "Retail" },
  { symbol: "VMART:NSE", name: "V-Mart Retail", sector: "Retail" },
  { symbol: "CAMPUS:NSE", name: "Campus Activewear", sector: "Retail" },
  { symbol: "DOMS:NSE", name: "DOMS Industries", sector: "Retail" },

  // ─── HOSPITALITY ────────────────────────────────────────────────
  { symbol: "INDHOTEL:NSE", name: "Indian Hotels (Taj)", sector: "Hospitality" },
  { symbol: "EIH:NSE", name: "EIH Ltd (Oberoi Hotels)", sector: "Hospitality" },
  { symbol: "LEMONTREE:NSE", name: "Lemon Tree Hotels", sector: "Hospitality" },
  { symbol: "CHALET:NSE", name: "Chalet Hotels", sector: "Hospitality" },
  { symbol: "MAHINDHOLIDAY:NSE", name: "Mahindra Holidays", sector: "Hospitality" },
  { symbol: "DEVYANI:NSE", name: "Devyani International (KFC/Pizza Hut)", sector: "Hospitality" },
  { symbol: "SAPPHIRE:NSE", name: "Sapphire Foods (KFC India)", sector: "Hospitality" },
  { symbol: "JUBLFOOD:NSE", name: "Jubilant FoodWorks (Domino's)", sector: "Hospitality" },

  // ─── TEXTILES & APPAREL ─────────────────────────────────────────
  { symbol: "PAGEIND:NSE", name: "Page Industries (Jockey)", sector: "Textiles" },
  { symbol: "TRIDENT:NSE", name: "Trident Ltd", sector: "Textiles" },
  { symbol: "WELSPUNLIV:NSE", name: "Welspun Living", sector: "Textiles" },
  { symbol: "KITEX:NSE", name: "Kitex Garments", sector: "Textiles" },
  { symbol: "RUPA:NSE", name: "Rupa & Company", sector: "Textiles" },
  { symbol: "SPORTKING:NSE", name: "Sportking India", sector: "Textiles" },

  // ─── SUGAR & AGRI-PROCESSING ────────────────────────────────────
  { symbol: "RENUKA:NSE", name: "Shree Renuka Sugars", sector: "Agri" },
  { symbol: "TRIVENI:NSE", name: "Triveni Engineering", sector: "Agri" },
  { symbol: "EIDPARRY:NSE", name: "EID Parry India", sector: "Agri" },
  { symbol: "DCMSHRIRAM:NSE", name: "DCM Shriram", sector: "Agri" },
  { symbol: "KRBL:NSE", name: "KRBL Ltd", sector: "Agri" },
  { symbol: "AVANTIFEED:NSE", name: "Avanti Feeds", sector: "Agri" },

  // ─── GEMS & JEWELLERY ───────────────────────────────────────────
  { symbol: "RAJESHEXPO:NSE", name: "Rajesh Exports", sector: "Retail" },
  { symbol: "KALYANKJIL:NSE", name: "Kalyan Jewellers", sector: "Retail" },
  { symbol: "SENCO:NSE", name: "Senco Gold", sector: "Retail" },
  { symbol: "JUBLPHARMA:NSE", name: "Jubilant Pharmova", sector: "Pharma" },

  // ─── ADDITIONAL REAL ESTATE ─────────────────────────────────────
  { symbol: "NESCO:NSE", name: "Nesco Ltd", sector: "Real Estate" },
  { symbol: "SUNTECKRELT:NSE", name: "Sunteck Realty", sector: "Real Estate" },
  { symbol: "KOLTEPATIL:NSE", name: "Kolte-Patil Developers", sector: "Real Estate" },
  { symbol: "ASHIANA:NSE", name: "Ashiana Housing", sector: "Real Estate" },

  // ─── ADDITIONAL DEFENCE & AEROSPACE ────────────────────────────
  { symbol: "MTAR:NSE", name: "MTAR Technologies", sector: "Infrastructure" },
  { symbol: "DATAPATTNS:NSE", name: "Data Patterns", sector: "Infrastructure" },
  { symbol: "PARAS:NSE", name: "Paras Defence", sector: "Infrastructure" },
  { symbol: "IDEAFORGE:NSE", name: "Ideaforge Technology", sector: "Infrastructure" },
  { symbol: "SOLARINDS:NSE", name: "Solar Industries India", sector: "Infrastructure" },
];

export const SECTOR_LIST = Array.from(new Set(STOCK_UNIVERSE.map(s => s.sector)));
